### PR TITLE
Box for the Espruino Pico.

### PR DESCRIPTION
**Pull request by valholl**
Hello. I've 3D printed a case for the Espruino Pico and if you are interested here is the OpenSCAD source.

Mostly it is meant to be useful when the Pico is to be deployed attached on an USB port (as opposed to battery-powered, standalone operation).

### CODE REVIEW

**Comment by gfwilliams** [comment]
Brilliant - thanks! Do you have a picture of it printed out? I'd love to see what it looks like in the flesh :)

**Comment by valholl** [comment]
On 2015-04-24 at 00:54:13 -0700, Gordon Williams wrote:
> Brilliant - thanks! Do you have a picture of it printed out? I'd love to see what it looks like in the flesh :)

not yet, but I can hopefully take one in the weekend

-- 
Elena ``of Valhalla''

**Comment by valholl** [comment]
On 2015-04-24 at 00:54:13 -0700, Gordon Williams wrote:
> Brilliant - thanks! Do you have a picture of it printed out? I'd love to see what it looks like in the flesh :)

Ehm, I took the picture, and then I utterly forgot about it :(

http://www.home.trueelena.org/files/121025-img_2733.jpg

these are the two variants: short walls that work as a usb "key" case 
and tall walls with room for the header pins.

(The url above may stop working in the next weeks/months, but feel free 
to download the image and use it under the same license as the Espruino 
documentation.)

-- 
Elena ``of Valhalla''

**Comment by gfwilliams** [comment]
great - thanks!

**Pull request merged**
