### PR TITLE
Add cover for espruino_box* versions

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
A slide-in cover for the espruino_box* cases

### CODE REVIEW

**Comment by gfwilliams** [comment]
Oh, wow! I like that :) Really really need to get my 3D printer working again!

**Comment by AlexanderBrevig** [comment]
Which printer do you have?
I'm in absolute love with 3d printing. It really is an enabler for making small one-off project looking awesome! Plus it's helpful being able to make small parts to fix stuff when it eventually breaks :)
I wish I had gotten one sooner, but I guess it's never to late to join the hype...

**Comment by gfwilliams** [comment]
I bought something called a SUMPOD about 3 years ago now - an earlier version of [this](http://www.sumpod.com/products/sumpod-basic-pickup)

Problem is there's sod all support, and it seems every version of SUMPOD is different. The version of Marlin they'd provided was really buggy, so I got a new version but now I've got to try and tweak it for the exact LCD, rotary encoder, heater, thermistor, gearing, end stops, feed rate, etc etc.

What software do you use to drive your printer? I was using repsnapper for a while, but again they keep updating the software and things keep breaking - it makes the whole process really hit and miss.

**Comment by AlexanderBrevig** [comment]
I'm using OpenSCAD and 123D Design for modelling, then [Cura](https://software.ultimaker.com/) for translating 3d to .gcode.

**Comment by AlexanderBrevig** [comment]
Sounds exhausting trying to tweak everything. That's one of the arguments I used for getting an Ultimaker 2 in the hopes that it's less time spent on tweaking and more time spent on printing.

So far it's been worth it I think :)

**Pull request merged**
