### PR TITLE
Add case for Espruino 1.4

### PR DESCRIPTION
**Pull request by AlexanderBrevig**
I added a case for 1.4 and tested it on an Ultimaker 2, works fine :)

### CODE REVIEW

**Comment by gfwilliams** [comment]
Fantastic - thanks!

**Comment by gfwilliams** [comment]
I don't suppose you feel like doing an Espruino Pico case? Someone asked for one yesterday and my 3D printer has been out of order for some time. I could do a design that I think would work as a starting point? :)

**Comment by AlexanderBrevig** [comment]
Sure, though I don't have a pico so might be hard to test. You wouldn't happen to have a STEP file for it (.stp)?

**Comment by gfwilliams** [comment]
Afraid not... Did you not back the KickStarter? For some reason I thought you had...

**Comment by AlexanderBrevig** [comment]
Sadly I missed out on it :(

**Comment by vimes79** [comment]
I can prob run off a laser cut case for the 1.4 
I can try and do a laser cut version for the Pico but the edges will have to be quite thin and as a result be brittle.
If I get time I will run one off on my RepRap in PLA or ABS with nice thin slices. I also have a bunch of sample bags of various other materials I have been sent over the past few months including a few rubbery like filaments, they might be worth a go as a layer of drop/knock protection rather then using hard ABS/PLA etc..

**Pull request merged**
